import { useMemo, useState } from 'react';
import { Check, X } from 'lucide-react';
import { Mascot, shuffleWithAnswer } from '../components/ui.jsx';

export default function Intake({ token, session, onDone }) {
  const quiz = session.metadata?.diagnostic_quiz || [];
  const [qIndex, setQIndex] = useState(0);
  const [picked, setPicked] = useState(null);
  const [revealed, setRevealed] = useState(false);
  const [results, setResults] = useState([]);

  const q = quiz[qIndex];
  const shuffled = useMemo(
    () => (q ? shuffleWithAnswer(q.options, q.correct_index) : { order: [], newCorrect: 0 }),
    [qIndex, quiz.length]
  );

  if (!q) return null;

  function choose(optIdx) {
    if (revealed) return;
    setPicked(optIdx);
    setRevealed(true);
    const isRight = optIdx === shuffled.newCorrect;
    setResults((r) => [...r, { question: q.question, chosen: q.options[shuffled.order[optIdx]], correct: isRight, tag: q.misconception_tag }]);
  }

  function next() {
    if (qIndex + 1 < quiz.length) {
      setQIndex(qIndex + 1);
      setPicked(null);
      setRevealed(false);
    } else {
      const answerText =
        'Warm-up quiz results (auto-generated by the app):\n' +
        results
          .map(
            (r, i) =>
              `Q${i + 1}: "${r.question}" → student chose "${r.chosen}" (${r.correct ? 'correct' : 'incorrect'})` +
              (r.tag && !r.correct ? ` [possible misconception: ${r.tag}]` : '')
          )
          .join('\n');
      onDone(answerText);
    }
  }

  return (
    <div className="fade-in" style={{ maxWidth: 640, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 18 }}>
      <div style={{ textAlign: 'center' }}>
        <span className="pill yellow">Quick warm-up · not graded</span>
        <h2 style={{ margin: '10px 0 4px', fontWeight: 900, fontSize: 26 }}>{session.active_topic}</h2>
        <p style={{ color: 'var(--ink-mid)', fontWeight: 700, margin: 0 }}>3 topic-specific diagnostic questions to calibrate your lesson depth.</p>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div className="dots">
          {quiz.map((_, i) => (
            <span key={i} className={`dot ${i < qIndex ? 'on' : i === qIndex ? 'now' : ''}`} />
          ))}
        </div>
        <span style={{ fontWeight: 900, color: 'var(--ink-mid)', fontSize: 13.5 }}>
          {qIndex + 1} / {quiz.length}
        </span>
      </div>

      <div className="card" key={qIndex} style={{ display: 'flex', flexDirection: 'column', gap: 12, padding: 24 }}>
        <div style={{ fontWeight: 900, fontSize: 19, lineHeight: 1.4 }}>{q.question}</div>
        {shuffled.order.map((origIdx, dispIdx) => {
          const isPicked = picked === dispIdx;
          const isAnswer = dispIdx === shuffled.newCorrect;
          const cls = revealed
            ? isAnswer ? 'choice right' : isPicked ? 'choice wrong' : 'choice'
            : isPicked ? 'choice picked' : 'choice';
          return (
            <button key={dispIdx} className={cls} onClick={() => choose(dispIdx)} disabled={revealed}>
              <span className="key">{'ABCD'[dispIdx]}</span>
              <span style={{ flex: 1 }}>{q.options[origIdx]}</span>
              {revealed && isAnswer && <Check size={19} color="var(--green)" />}
              {revealed && isPicked && !isAnswer && <X size={19} color="var(--red)" />}
            </button>
          );
        })}
        {revealed && (
          <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', gap: 10, alignItems: 'flex-start' }}>
            <span className={`pill ${picked === shuffled.newCorrect ? 'green' : 'blue'}`}>
              {picked === shuffled.newCorrect ? '✅ Nailed it' : '💡 Not quite — even better, now you\'ll see why'}
            </span>
            {q.explanation && (
              <p style={{ margin: 0, fontWeight: 700, color: 'var(--ink-mid)', fontSize: 14.5, lineHeight: 1.5 }}>{q.explanation}</p>
            )}
            <button className="btn3d green" onClick={next} style={{ alignSelf: 'flex-end' }}>
              {qIndex + 1 < quiz.length ? 'Next question →' : 'Build my lesson ✨'}
            </button>
          </div>
        )}
      </div>

      <Mascot
        token={token}
        session={session}
        screen="intake"
        text="No pressure — wrong taps here tell me exactly which concepts need extra attention in the upcoming animation!"
      />
    </div>
  );
}
